# Load from Pickle

In [1]:
import pandas as pd
import numpy as np

In [2]:
import os

print(os.getcwd()) #zeigt Arbeitsverzeichnis des Kernels
print(os.listdir()) #zeigt Dateien, die sich darin befinden

d:\iCloudDrive\Dokumente\Weiterbildung\Data Analyst\Abschlussprojekt\olist-marketplace-analysis\olist-marketplace-analysis\scripts\silver
['.gitkeep', 'silver_clean_order_payments_products_sellers.ipynb', 'silver_clean_order_payments_products_sellers.py']

In [3]:

last_layer = "bronze"
current_layer = "silver"
source_path = f"../{last_layer}/"
source_type = ".pkl"


bronze_tables_dict = pd.read_pickle(f"{source_path}{last_layer}_tables{source_type}")

print(f"Pickle Tables ({", ".join(bronze_tables_dict.keys())}) successsfully loaded into {current_layer}-Layer!")

Pickle Tables (bronze.csv_order_payments.csv, bronze.csv_products.csv, bronze.csv_sellers.csv) successsfully loaded into silver-Layer!

In [4]:
display(bronze_tables_dict["bronze.csv_order_payments.csv"])

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [5]:
df_order_payments = bronze_tables_dict["bronze.csv_order_payments.csv"]
df_products = bronze_tables_dict["bronze.csv_products.csv"]
df_sellers = bronze_tables_dict["bronze.csv_sellers.csv"]

# Start Cleaning order_payments

In [6]:
display(df_order_payments.head())

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

### Explain the columns

**order_id**: 
unique identifier of an order

**payment_sequential**: 
a customer may pay an order with more than one payment method. If he does so, a sequence will be created to accommodate all payments

**payment_type**: 
method of payment chosen by the customer

**payment_installments**: 
number of installments chosen by the customer

**payment_value**: 
transaction value

## Check Data Quality

In [7]:
print(df_order_payments.info())

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 8.1 MB
None

### payment_type

In [8]:
print(f"""
payment_type has the following values: 
{df_order_payments["payment_type"].value_counts()}
""")

payment_type has the following values:
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

### payment_installments

In [9]:
print(f"""
payment_installments has the following statistic values:
{df_order_payments["payment_installments"].describe()}
""")

payment_installments has the following statistic values:
count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

### payment_sequential

In [10]:
print(f"""
payment_sequential has the following statistic values:
{df_order_payments["payment_sequential"].describe()}
""")

payment_sequential has the following statistic values:
count    103886.000000
mean          1.092679
std           0.706584
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          29.000000
Name: payment_sequential, dtype: float64

### payment_value

In [11]:
print(f"""
payment_value has the following statistic values:
{df_order_payments["payment_value"].describe()}
""")

payment_value has the following statistic values:
count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

# Start Cleaning products

In [12]:
display(df_products.head())

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

### Explain the columns

**product_id**: 
unique product identifier

**product_category_name**: 
root category of product, in Portuguese

**product_name_lenght**: 
number of characters extracted from the product name


**product_description_lenght**: 
number of characters extracted from the product description


**product_photos_qty**: 
number of product published photos


**product_weight_g**:
product weight measured in grams


**product_length_cm**:
product length measured in centimeters


**product_height_cm**:
product height measured in centimeters


**product_width_cm**:
product width measured in centimeters

## Check Data Quality

In [13]:
print(df_products.info())

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 3.7 MB
None

### product_id

In [14]:
#check uniqueness of product_id

if df_products.product_id.nunique() == df_products.product_id.shape[0]:
    print("All product_id are unique")
else:
    print(f"""
    There are duplicates in product_id:
    {display(df_products[df_products.duplicated(keep=False)].sort_values(by="product_id"))}
    """)

All product_id are unique

### product_category_name

In [15]:
#check, if products have multiple categories

category_seperator_list = [",", ";", " "]

for sep in category_seperator_list:

    if df_products[(df_products.product_category_name != df_products.product_category_name.str.replace(sep,"")) & (df_products.product_category_name.isnull() == False)].shape[0] == 0:
        print(f"There are no products, which have multiple categories seperated with '{sep}'")

    else:
        print(f"There are products, which have multiple categories seperated with '{sep}':\n")
        print(df_products[(df_products.product_category_name != df_products.product_category_name.str.replace(sep,"")) & (df_products.product_category_name.isnull() == False)][["product_id", "product_category_name"]])

There are no products, which have multiple categories seperated with ','
There are no products, which have multiple categories seperated with ';'
There are no products, which have multiple categories seperated with ' '

In [16]:
print(f"product_category_name has {df_products.product_category_name.nunique()} unique categories")
print(f"In product_category_name {df_products.product_category_name.isnull().sum()} of {df_products.shape[0]} products don't have any category (NULL values)")

product_category_name has 73 unique categories
In product_category_name 610 of 32951 products don't have any category (NULL values)

### product_description_lenght

In [17]:
print(f"product_description_lenght is from {df_products.product_description_lenght.min():.0f} up to {df_products.product_description_lenght.max():.0f} characters and the mean description lenght is {df_products.product_description_lenght.mean():.0f}")
print(f"In product_description_lenght {df_products.product_description_lenght.isnull().sum()} of {df_products.shape[0]} rows are NULL values")

product_description_lenght is from 4 up to 3992 characters and the mean description lenght is 771
In product_description_lenght 610 of 32951 rows are NULL values

### product_photos_qty

In [18]:
print(f"product_photos_qty is from {df_products.product_photos_qty.min():.0f} up to {df_products.product_photos_qty.max():.0f} photos per product and the mean photo quantity is {df_products.product_photos_qty.mean():.0f}")
print(f"In product_photos_qty {df_products.product_photos_qty.isnull().sum()} of {df_products.shape[0]} products don't have any photo")

product_photos_qty is from 1 up to 20 photos per product and the mean photo quantity is 2
In product_photos_qty 610 of 32951 products don't have any photo

###  product_weight_g, product_length_cm, product_height_cm, product_width_cm

In [28]:
#product_weight_g

print(f"product_weight_g is from {df_products.product_weight_g.min():.0f} up to {df_products.product_weight_g.max():.0f} grams per product and the mean weight is {df_products.product_weight_g.mean():.0f}")
print(f"In product_weight_g {df_products.product_weight_g.isnull().sum()} of {df_products.shape[0]} products don't have any weight")

product_weight_g is from 0 up to 40425 grams per product and the mean weight is 2276
In product_weight_g 2 of 32951 products don't have any weight

In [30]:
#product_length_cm

print(f"product_length_cm is from {df_products.product_length_cm.min():.0f} up to {df_products.product_length_cm.max():.0f} centimetres per product and the mean lenghth is {df_products.product_length_cm.mean():.0f}")
print(f"In product_length_cm {df_products.product_length_cm.isnull().sum()} of {df_products.shape[0]} products don't have any length")

product_length_cm is from 7 up to 105 centimetres per product and the mean lenghth is 31
In product_length_cm 2 of 32951 products don't have any length

In [31]:
#product_length_cm

print(f"product_height_cm is from {df_products.product_height_cm.min():.0f} up to {df_products.product_height_cm.max():.0f} centimetres per product and the mean height is {df_products.product_height_cm.mean():.0f}")
print(f"In product_height_cm {df_products.product_height_cm.isnull().sum()} of {df_products.shape[0]} products don't have any height")

product_height_cm is from 2 up to 105 centimetres per product and the mean height is 17
In product_height_cm 2 of 32951 products don't have any height

In [ ]:
#Are there rows, where all size columns are null?

df_products[df_products[["product_weight_g", "product_length_cm", "product_height_cm", "product_width_cm"]].isnull().all(axis=1)]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN